# The port to run the service on.
port = 3000

# The max upload size in bytes.
max_upload_size = 5_000_000

# The path to the adjectives file, which contains a list of adjectives separated
# by newlines. Terminating newlines are ignored.
adjectives_file = "adjectives.txt"

# The path to the nouns file, which contains a list of nouns separated by
# newlines. Terminating newlines are ignored.
nouns_file = "animals.txt"

# The S3 bucket to upload files to.
s3_bucket = ""

# The S3 region to connect to.
s3_region = ""

# The S3 endpoint to connect to, if not AWS.
# s3_endpoint = ""
